services:
  stube:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data/stube/public/uploads:/app/public/uploads
      - ./data/stube/public/posters:/app/public/posters
      - ./data/stube/public/attachments:/app/public/attachments
  mongo:
    image: "mongo:4.4.6"
    volumes:
      - ./data/mongo:/data/db